### ISSUE TITLE
Option for Inline Files?

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/filefield_paths#16]
Hey @indigoxela, thanks for porting and maintaining this module!

I'm curious if you think this module would be a good place for specifying tokens for _inline_ uploaded files, ones that are usually uploaded through CKEditor? Right now I believe all inline files just get dropped into the same directory.

**Comment by indigoxela** [comment]
> I'm curious if you think this module would be a good place for specifying tokens for inline uploaded files, ones that are usually uploaded through CKEditor

That might be possible, but potentially tricky. Currently that path is controlled by the per-filter format settings, and the image browser allows to select existing files (sure, that browser can also be enabled per field, but in the filter format that setting is always on).

Given the name of the module "Field (Field) Paths" - it's rather supposed to act on fields. But as the files in the editor (and imce) are now managed files, too... I see a potential there. Personally, I've not used a combination of this module and the image browser, yet. Might need some consideration.

@quicksketch what's your use case? Can you describe it a bit?

**Comment by quicksketch** [comment]
I have a client that previously used Insert module on Drupal 7, now they've switched to using the easier inline files provided by Backdrop core and CKEditor. They previously had a nice directory structure like `images/blog/[filename]`, `images/[other-type]/[filename]`, etc. With Backdrop core they are only allowed a single directory for _all_ content types. However, image reuse is possible in Backdrop so it's not really guaranteed that all images will always be 1-to-1 with the content type name. But the preference is that at the time of upload, a content type could be inserted into the file upload location.

I'm not totally sure if it belongs in this module or not either. Seems like there's some potential overlap but maybe it would be better as a separate module.

**Comment by indigoxela** [comment]
I wonder if/when they'd even be aware that images are in subdirectories, as the image browser won't show that info. OK, it _is_ visible when inserting (in the src text input field after selecting).
What's the benefit of a more or less invisible directory structure, that's not guaranteed, anyway?

Another thing to consider: would people know that this module provides that functionality for inline images when searching for that feature in existing modules?

Some things might be difficult: we can not and IMO should not provide the advanced features (like (retro-)actively updating paths).
These features are already problematic if a field also allows to select existing images (which is why I don't use this module in combination with the image browser). Too many possible pitfalls.
