### ISSUE TITLE
Another Ubercart/Filefield paths crash

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/filefield_paths#27]
This came up on a live site, reported by the store manager when "creating an order" (in Ubercart). I haven't been able to reproduce the error (yet) on a dev site, but will still report it here.

The error message is:

Message | Error: Call to undefined method stdClass::bundle() in filefield_paths_field_storage_pre_update() (line 363 of mysite/modules/contrib/filefield_paths/filefield_paths.module).

Lines 363–365 are:

```
  $bundle = $entity->bundle();
  if ($entity_info['fieldable']) {
    $field_instances = field_info_instances($entity_type, $bundle);
```

So the error is happening when `$entity` doesn't have a `bundle()` method. (I can't tell you what type of $entity it is until I can reproduce it.) But I think it's not required that every entity have that method, right?

So that my store manager can do her thing, I hot-fixed the site with this:

```
  $bundle = $entity->bundle() ?? NULL;
  if ($bundle && $entity_info['fieldable']) {
    $field_instances = field_info_instances($entity_type, $bundle);
```

Seems like filefield_paths should probably be hardened in this way (although using `isset()` since old PHP doesn't support `??`). Even if it is the case (which seems plausible) that Ubercart is doing something squirrely (eichhörnchenlich?) with its entities.

Pinging @argiepiano, just because it's Ubercart and entities, for any insights.

**Comment by bugfolder** [comment]
Actually, the first line should be:

```
  $bundle = method_exists($entity, 'bundle') ? $entity->bundle() : NULL;
```

Because (as I just learned) `??` works for missing array keys but not missing methods.

**Comment by argiepiano** [comment]
@bugfolder, all entities MUST have a bundle method, as per the definition of `EntityInterface`, which makes it required.

I believe the issue must happen after tying to create a blank line item in an order. If you look at Ubercart's line 543 of function `uc_order_edit_products_add_blank()` in file `uc_order.uc_order_pane.inc` you'll see that the code there (inherited from D7) is creating a "product" (my guess is that this was intended to be a `uc_order_product` entity), but instead of using `entity_create()` it's simply creating a `stdClass()` object, which doesn't have a `bundle` method.

I haven't tested this, but you should try to reproduce by creating a blank line item in an order.

The solution (if this indeed is the cause) is to modify the code of `uc_order_edit_products_add_blank()` to create the and entity object instead of a stdClass.

**Comment by bugfolder** [comment]
Thanks, @argiepiano, I'll follow that line of inquiry later today. And I'll take this over to the UC issue queue and close it here.

**Comment by indigoxela** [comment]
A little tongue-in-cheek: glad, that the filefield_path module's a helpful debugging tool to fix issues in ubercart. :stuck_out_tongue_winking_eye:
